### PR TITLE
Refactor archive action

### LINKED ISSUE #114: Refactor archive action
## Task Summary

📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## To Do

- [x] Take org_id instead org_config
- [x] ISCN data model code can be moved to new file

### PR DESCRIPTION
**Pull request by makew0rld**
Fixes #114

Diff is pretty ugly because I changed indentation, but using commit diffs should help. Changes are minor overall.

### CODE REVIEW

**Comment by benhylau** [comment]
@makeworld-the-better-one what I'd like is for this to become its own private method https://github.com/starlinglab/integrity-backend/blob/1506ce01c1adc83f2bfa39fe115b4c708b3e5014/integritybackend/actions.py#L198-L240

Each step being it's own private method, so:
- there is more clarity into what each step takes as input
- they are independently testable
- the `_archive` method can be 30 lines instead of [this 300+ line monster](https://github.com/starlinglab/integrity-backend/blob/1506ce01c1adc83f2bfa39fe115b4c708b3e5014/integritybackend/actions.py#L61-L403)

Basically each step, or groupings of these, can potentially spin off to its own method:
- # Verify ZIP contents are valid and expected
- # Extract content file
- # Generate content hashes and verify
- # Extract metadata files
- # Sign with authsign
- # Register on OpenTimestamps and add that file to zip
- # Get archive ZIP hashes
- # Rename archive zip to SHA-256 of itself
- # Encrypt archive ZIP
- # Get encrypted ZIP hashes
- # Rename encrypted ZIP to SHA-256 of itself
- # Register encrypted ZIP on ISCN
- # Register encrypted ZIP on Numbers Protocol
- # Generate file that contains all the hashes

Can you and @galargh think on improving this a bit?

**Comment by makeworld-the-better-one** [comment]
Would be good to get #119 merged into here before further work begins.

**Comment by makeworld-the-better-one** [comment]
#119 is merged in and so is main, meaning this branch is up to date, diffs make more sense, and work can begin.

**Comment by makeworld-the-better-one** [comment]
#130 will help improve the function as well, and should be merged into this PR after it's merged into dev.

**Comment by makeworld-the-better-one** [comment]
TODO: after reregister script is merged in, update it here to use the archival functions this PR creates.

**Comment by makew0rld** [comment]
I think this is as much breaking up of the archive function as I can do without reducing readability. Most of the sections left are around three lines long and are ingrained into the function, and so wouldn't be helped by being place in a separate function.

**Review by benhylau — APPROVED** [review]

**Pull request merged**
